file_format: "1"
id: spooderlily
name: spooderlily
type: shield
url: https://github.com/kaloyyyy/zmk-config-spooderlily
requires: [pro_micro]
features:
  - keys
  - underglow
siblings:
  - spooderlily_left
  - spooderlily_right
